services:
  postgres:
    image: postgres:16-alpine
    container_name: cake_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cake
      POSTGRES_PASSWORD: cake
      POSTGRES_DB: cake
    volumes:
      - cake_pg_data:/var/lib/postgresql/data

volumes:
  cake_pg_data:
